import type { Metadata } from "next";
import "@/app/globals.css";
import AuthWrapper from "@/app/auth/auth-wrapper";
import SessionProviderWrapper from "@/components/auth/SessionProviderWrapper";
import NavWrapper from "@/components/dashboard/nav-wrapper"; // Import new client component

export const metadata: Metadata = {
  title: "Portfolio Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{ children: React.ReactNode; session: any }>) {
  return (
    <html lang="en">
      <body>
        <SessionProviderWrapper session={session}>
          <AuthWrapper>{children}</AuthWrapper>
          <NavWrapper /> {/* this is rendered conditionally so that landing page doesnt see navbar*/}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
