import type { Metadata } from "next";
import "@/app/globals.css";
import AuthWrapper from "@/app/auth/auth-wrapper";
import SessionProviderWrapper from "@/components/auth/SessionProviderWrapper";
import NavWrapper from "@/components/dashboard/nav-wrapper";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: "Portfolio Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* SessionProviderWrapper automatically updates the session */}
        <SessionProviderWrapper>
          <AuthWrapper>
            <NavWrapper />
            {children}
          </AuthWrapper>
        </SessionProviderWrapper>
        <ToastContainer 
        position="bottom-right"
        autoClose={5000}
        hideProgressBar={false}
        newestOnTop={true}
        closeButton={true}
        /> {/* This is needed to render the toasts which i use instead of alert() */}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
